# Generated by Django 3.2 on 2021-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogogo', '0003_servicetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_count', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
