# Generated by Django 3.2 on 2021-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogogo', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order_count',
            field=models.PositiveIntegerField(),
        ),
    ]
