# Generated by Django 3.2 on 2021-04-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogogo', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='ogogo.service'),
        ),
        migrations.AddField(
            model_name='servicetime',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_time', to='ogogo.service'),
        ),
    ]
